server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

#设置Feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout:  5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以书面级别监控哪个接口
    com.myself.springcloud.service.PaymentFeignService: debug
    #关于日志级别:不要和Feign的日志级别。可以理解为一个是小院子(feign)，一个是大院子(log)。大院子中有小院子
    #日志级别分为:debug -> info -> error -> fatel,日志输出的时候, 只会输出大于等于该级别的日志, 也就是设置了INFO之后, DEBUG是不会被输出, 只会输出INFO、ERROR和FATAL级别的日志.
    #feign的日志级别分为:NONE,BASIC,HEADER,FULL.具体可以看脑图
