server:
  port: 80


eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-provider-hystrix-order

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与提供者不一样。

#  client:
#    config:
#      #这里填具体的服务名称（也可以填default，表示对所有服务生效）
#      app-order:
#        #connectTimeout和readTimeout这两个得一起配置才会生效
#        connectTimeout: 5000
#        readTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # 设置hystrix的超时时间为3000ms, 之后才调用降级方法.熔断器超时时间，默认：1000ms